<?php
//model for student extra activity form
namespace app\models;
use Exception;
use Yii;
use yii\base\Model;
use yii\db\ActiveRecord;
class StudentExtraForm extends Model{
    public function rules(){
        return parent::rules(); // TODO: Change the autogenerated stub
    }
    public function insertStudentExtra(){
    }
}
?>
